name: PR Comment

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  comment-pr:
    if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
    uses: bgd-labs/github-workflows/.github/workflows/comment.yml@main
    secrets:
      READ_ONLY_PAT: ${{ secrets.READ_ONLY_PAT }}
  comment-commit:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    uses: bgd-labs/github-workflows/.github/workflows/comment.yml@main
